[package]
name = "http_server_single_thread"
version = "0.1.0"
authors = ["alexa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
